### ISSUE TITLE
Setup Dockerized Development Postgress Database

### ISSUE THREAD

**Issue by NathanGrenier** [NathanGrenier/SOEN-341#16]
Setup a docker compose file to launch a postgress database in a docker container for development purposes.

Data should be seeded to this database whenever it's run.

**Comment by briantkatch** [comment]
Personally I've always run Postgres locally outside of a Docker container because spinning up a brand-new Postgres every time is a little pointless, but I guess this saves having to perform schema migrations on the dev database.

I guess there should be a sql file that is part of the repository that contains the test data so that changes to that data can be version-managed

**Comment by NathanGrenier** [comment]
> Personally I've always run Postgres locally outside of a Docker container because spinning up a brand-new Postgres every time is a little pointless, but I guess this saves having to perform schema migrations on the dev database.
> 
I set it up using docker compose, so it's just 1 command to get it up and running. 
> I guess there should be a sql file that is part of the repository that contains the test data so that changes to that data can be version-managed
This is managed by the ORM that we're using (Prisma). You can check out Prisma migrations and seeding on their docs.
